services:
  web:
    image: ghcr.io/indiejoseph/wine-pairing-chatbot-poc:latest
    container_name: web
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=4000
      - HOSTNAME=0.0.0.0
    ports:
      - 4000:4000
