services:
  web:
    image: ghcr.io/indiejoseph/wine-pairing-chatbot-poc:latest
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=${PORT}
    ports:
      - 4000:4000
