services:
  showtime-ai-api:
    image: ghcr.io/indiejoseph/wine-pairing-chatbot:latest
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 3000:3000
    depends_on:
      - redis