version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 443:443
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./challenges:/var/www/challenges
      - ./certs:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
      - ./challenges:/var/www/challenges
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  memcached:
    image: memcached:latest
    container_name: memcached_container
    networks:
      - app-network

  # api:
  #   image: node:latest
  #   container_name: api_container
  #   working_dir: /app
  #   volumes:
  #     - ./packages/api:/app
  #   command: npm run dev
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - reverse-proxy

networks:
  app-network: